CREATE TABLE IF NOT EXISTS individual_info (
    id INT PRIMARY KEY AUTO_INCREMENT,
    indivi_num VARCHAR(10) NOT NULL,
    add_day DATE NOT NULL,
    left_day DATE,
    gone BOOLEAN NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS born_info (
    id INT PRIMARY KEY AUTO_INCREMENT,
    pig_id INT NOT NULL,
    born_day DATE NOT NULL,
    born_num INT NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_pig_id
    FOREIGN KEY (pig_id)
        REFERENCES individual_info(id)
        ON DELETE RESTRICT ON UPDATE RESTRICT
);
